config/routes.rb
GdriveFeed::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # @todo: use :only => [:show, :...] in resources to be able to override create method
  get 'monitored_resources/create_with/:gid', :to => 'monitored_resources#create_with', :as => 'create_with'

  get 'calculate_time_distance_to_previous', :to => 'resources#calculate_time_distance_to_previous', :as => 'calculate_time_distance_to_previous'
  get 'calculate_optimal_threshold', :to => 'resources#calculate_optimal_threshold', :as => 'calculate_optimal_threshold'
  get 'show_threshold', :to => 'resources#show_threshold', :as => 'show_threshold'

  get 'welcome', :to => 'management/management#welcome', :as => 'welcome'
  namespace :management do
    get 'new_researcher', :to => 'management#new_researcher'
    post 'create_researcher', :to => 'management#create_researcher'
    get 'grant_access', :to => 'management#grant_access'
  end

  resources :monitored_resources do
    collection do
      get 'grant_access'
    end

    member do
      get 'index_structure'
      get 'create_working_sessions'
      get 'calculate_all_working_sessions'
      get 'update_resources_metadata'
      get 'garbage_collection_mark'
      get 'garbage_collection_sweep'
    end

    resources :permissions do
      collection do
        get 'refresh'
      end
    end

    resources :document_groups do
      collection do
        get 'new_samedocument'
      end
    end

    resources :permission_groups
    resources :resources do
      member do
        get 'refresh_revisions'
        get 'download_revisions'
        get 'merged_revisions/:rev_id', :action => :merged_revisions, :as => 'merged_revisions'
        get 'show_svg'
      end
    end
    resources :reports do
      collection do
        get 'generate'
        get 'remove'
      end
    end
  end

  get 'reports/metareport', to: 'reports#metareport', :as => 'reports_metareport'
  get 'reports/statistics', to: 'reports#statistics', :as => 'reports_statistics'
  get 'reports/generate_metareport', to: 'reports#generate_metareport', :as => 'reports_generate_metareport'

  resources :monitored_periods
  resources :period_groups

  root :to => 'management/management#welcome'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/document_group.rb
class DocumentGroup < ActiveRecord::Base
  has_many :resources

  # @todo only finds classes within the file
  def self.descendants
    ObjectSpace.each_object(::Class).select {|klass| klass < self }
  end

  def find(monitored_resource=nil, period=nil)

  end

  def self.find_resources(monitored_resource=nil, period=nil)
    group_ids = DocumentGroup
      .where(:monitored_resource_id => monitored_resource.id).map {|dg| dg.id}

    query = ["SELECT r.id,r.document_group_id FROM resources r "]
    query.first << "JOIN revisions rr ON r.id=rr.resource_id WHERE "

    unless period.blank?
      query.first << " rr.modified_date  <= ? "
      query.push period.end_date
    end

    query.first << "GROUP BY r.id"

    return Resource
      .joins("revisions")
      .where("document_group_id IN(#{group_ids.join(',')})")
      .where()
  end

  def self.find_collaborated_document_groups_until(monitored_resource=nil, period=nil,limit_to_global=false)
    query = ["SELECT r.document_group_id FROM resources r JOIN revisions rr ON rr.resource_id=r.id JOIN permissions p ON rr.permission_id=p.id JOIN permission_groups_permissions pgp ON p.id=pgp.permission_id"]

    where = ""
    unless monitored_resource.blank?
      where = " WHERE r.monitored_resource_id=? AND document_group_id IS NOT NULL "
      query.push monitored_resource.id
    end

    unless period.blank?
      if where.empty?
        where = " WHERE "
      else
        where << " AND "
      end

      where << ' rr.modified_date <= ?'
      query.push period.end_date
    end

    query.first << where

    # only global collaboration
    if limit_to_global
      query.first << " GROUP BY r.document_group_id HAVING COUNT(DISTINCT pgp.permission_group_id) > 1"
    else
      query.first << " GROUP BY r.document_group_id HAVING COUNT(DISTINCT p.id) > 1"
    end

    query_sql = ActiveRecord::Base.send(:sanitize_sql_array, query)
    results = ActiveRecord::Base.connection.exec_query(query_sql)

    document_group_ids = results.map {|r| r['document_group_id']}
    if document_group_ids.blank?
      return []
    else
      resources = Resource
        .where("resources.document_group_id IN (#{document_group_ids.join(",")})")
        .where(:monitored_resource_id => monitored_resource.id)
      return resources.map {|r| r.id }
    end
  end

  def self.count(monitored_resource=nil)
    self.find(monitored_resource).count
  end

  #def self.batch_create_identical
  #  query = "SELECT r.title, GROUP_CONCAT(r.id) FROM resources r WHERE monitored_resource_id=4 AND mime_type !='application/vnd.google-apps.folder' GROUP BY r.title HAVING COUNT(r.id) > 1"
  #end
end

app/controllers/document_groups_controller.rb
class DocumentGroupsController < ApplicationController
  before_action :set_document_group, only: [:show, :edit, :update, :destroy]

  # GET /monitored_resources/1/document_groups
  def index
    @monitored_resource = MonitoredResource
      .where(:id => params[:monitored_resource_id])
      .where(:user_id => current_user.id)
      .first()
    @document_groups = DocumentGroup.where(:monitored_resource_id => params[:monitored_resource_id])
  end

  # GET /monitored_resources/1/document_groups/1
  def show
  end

  # GET /document_groups/new
  def new
    @monitored_resource = MonitoredResource
    .where(:id => params[:monitored_resource_id])
    .where(:user_id => current_user.id)
    .first()

    if @monitored_resource.nil?
      redirect_to monitored_resources_path, :notice => "Monitored Resource with ID #{params[:id]} could not be found!"
    end

    @document_group = DocumentGroup.new
    @document_group.monitored_resource_id = @monitored_resource.id
  end

  # GET /document_groups/1/edit
  def edit
  end

  # POST /document_groups
  # POST /document_groups.json
  def create
    @document_group = DocumentGroup.new(document_group_params)

    respond_to do |format|
      if @document_group.save
        format.html { redirect_to monitored_resource_document_groups_path(@document_group.monitored_resource_id), notice: 'Document group was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /document_groups/1
  # PATCH/PUT /document_groups/1.json
  def update
    respond_to do |format|
      if @document_group.update(document_group_params)
        format.html { redirect_to @document_group, notice: 'Document group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_groups/1
  # DELETE /document_groups/1.json
  def destroy
    @document_group.destroy
    respond_to do |format|
      format.html { redirect_to document_groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document_group
      @monitored_resource = MonitoredResource.find(params[:monitored_resource_id])
      @document_group = DocumentGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_group_params
      params[:document_group]
      params.require(:document_group).permit(:monitored_resource_id, :title, :head_id, :resource_ids => [])
    end
end

app/helpers/document_groups_helper.rb
module DocumentGroupsHelper
end

app/views/document_groups/_form.html.erb
<%= form_for [@monitored_resource,@document_group] do |f| %>
  <% if @document_group.errors.any? %>
    <div data-alert class="alert-box warning round" id="error_explanation">
      <h2><%= pluralize(@document_group.errors.count, "error") %> prohibited this document_group from being saved:</h2>

      <ul>
      <% @document_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>

  <%= f.hidden_field :monitored_resource_id %>
    <div class="row">
      <div class="large-12 columns">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="row">
      <div class="large-6 columns">
        <%= f.label :resources %>
        <%= f.collection_select :resource_ids, @monitored_resource.resources.ungrouped(@document_group), :id, :doc_group_title, {}, { :size=> 20, :multiple => true} %>
      </div>
      <div class="large-6 columns">
        <p>Selected Documents:</p>
        <ul>
        <% @document_group.resources.each do |resource| %>
            <li><%= resource.title %></li>
        <% end %>
        </ul>
      </div>
    </div>
    <div class="row">
       <div class="large-12 columns"><%= f.submit :class => 'button tiny' %></div>
    </div>
<% end %>

app/views/document_groups/_form_samedocument.html.erb
<%= form_for [@monitored_resource,@document_group] do |f| %>
  <% if @document_group.errors.any? %>
    <div data-alert class="alert-box warning round" id="error_explanation">
      <h2><%= pluralize(@document_group.errors.count, "error") %> prohibited this document_group from being saved:</h2>

      <ul>
      <% @document_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>

  <%= f.hidden_field :monitored_resource_id %>
    <div class="row">
      <div class="large-12 columns">
        <%= f.label :title %>
        <%= f.text_field :title, disabled: true %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= f.label :type %>
        <%= f.collection_select :types, @monitored_resource.permissions, :id, :title_usage %>
      </div>
    </div>
    <div class="row">
       <div class="large-12 columns"><%= f.submit :class => 'button tiny' %></div>
    </div>
<% end %>

app/views/document_groups/edit.html.erb
<h1>Editing SameDocument</h1>

<%= render 'form' %>

<%= link_to 'Back', monitored_resource_document_groups_path, :class => 'button tiny' %>

app/views/document_groups/index.html.erb
<% content_for :title, 'List of Document Groups' %>
<h2>Document Groups for <%= @monitored_resource.title %></h2>

<%= link_to 'Create New', new_monitored_resource_document_group_path, :class => 'button tiny' %>

<% if @document_groups.length.eql? 0 %>
    <p><i>There are no document groups available, yet. Go create one!</i></p>
<% else %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @document_groups.each do |document_group| %>
      <tr>
        <td><%= document_group.title %></td>
        <td><%= link_to 'Edit', edit_monitored_resource_document_group_path(@monitored_resource, document_group) %></td>
        <td><%= link_to 'Destroy', monitored_resource_document_group_path(@monitored_resource.id, document_group), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<%= link_to 'Create New', new_monitored_resource_document_group_path, :class => 'button tiny' %>

app/views/document_groups/new.html.erb
<% content_for :title, 'New Document Group' %>
<h2>New DocumentGroup</h2>
<p>Pleases choose type of document group</p>

<%= render 'form' %>

<%= link_to 'Back', monitored_resource_document_groups_path, :class => 'button tiny' %>

app/views/document_groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_document_group_path(@document_group) %> |
<%= link_to 'Back', document_groups_path %>