config/routes.rb
GdriveFeed::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # @todo: use :only => [:show, :...] in resources to be able to override create method
  get 'monitored_resources/create_with/:gid', :to => 'monitored_resources#create_with', :as => 'create_with'

  get 'calculate_time_distance_to_previous', :to => 'resources#calculate_time_distance_to_previous', :as => 'calculate_time_distance_to_previous'
  get 'calculate_optimal_threshold', :to => 'resources#calculate_optimal_threshold', :as => 'calculate_optimal_threshold'
  get 'show_threshold', :to => 'resources#show_threshold', :as => 'show_threshold'

  get 'welcome', :to => 'management/management#welcome', :as => 'welcome'
  namespace :management do
    get 'new_researcher', :to => 'management#new_researcher'
    post 'create_researcher', :to => 'management#create_researcher'
    get 'grant_access', :to => 'management#grant_access'
  end

  resources :monitored_resources do
    collection do
      get 'grant_access'
    end

    member do
      get 'index_structure'
      get 'create_working_sessions'
      get 'calculate_all_working_sessions'
      get 'update_resources_metadata'
      get 'garbage_collection_mark'
      get 'garbage_collection_sweep'
    end

    resources :permissions do
      collection do
        get 'refresh'
      end
    end

    resources :document_groups do
      collection do
        get 'new_samedocument'
      end
    end

    resources :permission_groups
    resources :resources do
      member do
        get 'refresh_revisions'
        get 'download_revisions'
        get 'merged_revisions/:rev_id', :action => :merged_revisions, :as => 'merged_revisions'
        get 'show_svg'
      end
    end
    resources :reports do
      collection do
        get 'generate'
        get 'remove'
      end
    end
  end

  get 'reports/metareport', to: 'reports#metareport', :as => 'reports_metareport'
  get 'reports/statistics', to: 'reports#statistics', :as => 'reports_statistics'
  get 'reports/generate_metareport', to: 'reports#generate_metareport', :as => 'reports_generate_metareport'

  resources :monitored_periods
  resources :period_groups

  root :to => 'management/management#welcome'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/monitored_resources_controller.rb
require 'rest_client'
require 'time_diff'

class MonitoredResourcesController < ApplicationController
  #before_filter :refresh_token!, only: [:new, :index_structure]
  before_action :set_monitored_resource, only: [:show, :index_structure, :create_working_sessions,
                                                :calculate_all_working_sessions, :update_resources_metadata,
                                                :garbage_collection_mark, :garbage_collection_sweep]

  def index
    @monitored_resources = current_user.monitored_resources
  end

  def new
    authorize! :manage, @monitored_resource
    refresh_token!

    @folders = DriveFiles.retrieve_all_root_folders(current_user.token)
    @monitored_resources_ids = current_user.monitored_resources_ids
    @monitored_resources = current_user.monitored_resources # for navigation only
  end
  
  def create_with
    authorize! :create, @monitored_resource
    @monitored_resource = MonitoredResource.where(monitored_resource_params).first_or_create
    @monitored_resource.update_metadata(current_user.token)
    @monitored_resource.update_permissions(current_user.token)

    redirect_to @monitored_resource, :notice => "New monitored resource '#{@monitored_resource.title}' successfully created"
  end
  
  def show
    respond_to do |format|
      format.html {
        # wrong parameter passed -> return
        redirect_to root_path, :alert => "The resource does not exist!" if @monitored_resource.blank?
      }
      format.json { render json: ResourcesDatatable.new(view_context, @monitored_resource) }
      #format.json { render json: @monitored_resource }
    end
  end

  def index_structure
    authorize! :manage, @monitored_resource
    refresh_token!

    @monitored_resource.update_metadata(current_user.token)
    @monitored_resource.index_structure(current_user.id, current_user.token, @monitored_resource.gid)

    now = Time.now
    diff = Time.diff(@monitored_resource.structure_indexed_at, now)
    @monitored_resource.update_attribute(:structure_indexed_at, now)

    redirect_to @monitored_resource, :notice => "Structure has last been indexed #{diff[:diff]} hours ago!"
  end

  def garbage_collection_mark
    authorize! :manage, @monitored_resource
    refresh_token!

    # un-mark every resource
    Resource
      .where(:monitored_resource_id => @monitored_resource.id)
      .update_all(:gc_marked => nil)

    @monitored_resource.garbage_collection(current_user.id, current_user.token, @monitored_resource.gid)

    redirect_to @monitored_resource, :notice => "Gargabe collection: marking phase is in progress!"
  end

  def garbage_collection_sweep
    authorize! :manage, @monitored_resource

    @monitored_resource.gc_delete_marked

    redirect_to @monitored_resource, :notice => "Gargabe collection: sweeping completed!"
  end

  def create_working_sessions
    authorize! :manage, @monitored_resource

    @monitored_resource.create_working_sessions
    redirect_to @monitored_resource, :notice => "Revisions are aggregated! This might take a while!"
  end

  def calculate_all_working_sessions
    authorize! :manage, @monitored_resource

    @monitored_resource.calculate_all_working_sessions
    redirect_to @monitored_resource, :notice => "All possible working sessions between 3-40 minutes are calculated. This might take a while!"
  end

  def update_resources_metadata
    authorize! :manage, @monitored_resource
    refresh_token!

    @monitored_resource.update_resources_metadata(current_user.token)
    redirect_to @monitored_resource, :notice => "Metadata of all resource is begin updated. This might take a while!"
  end

  def grant_access

  end

  # @TODO DEPRECATED - SHOULD BE REMOVED IF NO LONGER NEEDED

  # Downlaods revisions for files that have none (revisions.eql? 0)
  # can be removed once the 401 - unauthorized request can be handled!
  def missing_revisions
    resources = Resource
    .joins('LEFT OUTER JOIN revisions ON resources.id=revisions.resource_id')
    .where('monitored_resource_id=? AND revisions.resource_id IS NULL AND mime_type != "application/vnd.google-apps.folder"',  @monitored_resource.id)

    resources.each do |resource|
      resource.retrieve_revisions(current_user.token)
    end
    redirect_to @monitored_resource, :notice => "Missing Revisions are being refreshed!"
  end

  def download_revisions
    @monitored_resource.resources.google_resources.each do |resource|
      # each function call will result in a new delayed job, each revision download in another one
      resource.download_revisions(current_user.token)
    end
    redirect_to @monitored_resource, :notice => "Revisions are being downloaded! This might take a while!"
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_monitored_resource
    @monitored_resource = MonitoredResource
      .where(:id => params[:id]).first

    # wrong parameter passed -> return
    return nil if @monitored_resource.blank?

    # Authorize object permission - @todo: better way to solve this via cancan?
    shared = current_user.shared_resources.map {|r| r.id }
    @monitored_resource = nil unless ((@monitored_resource.user_id == current_user.id) || shared.include?(@monitored_resource.id))

    # CANCAN - authorize read access
    authorize! :read, @monitored_resource
  end

  # Never trust parameters from the scary internet, only allow the white index through.
  def monitored_resource_params
    par = { :gid => params[:gid], :user_id => current_user.id }
  end
end

app/helpers/monitored_resources_helper.rb
module MonitoredResourcesHelper
end

app/views/monitored_resources/index.html.erb
<% content_for :title, 'List of Monitored Resources' %>
<h3>Monitored Resources</h3>

<%= link_to "Create new", new_monitored_resource_path, :class => 'button tiny' %>

<% unless @monitored_resource.nil? %>
<div data-alert class="alert-box info radius">
	There are no monitored resources yet.
  <a href="#" class="close">&times;</a>
</div>
<% else %>
    <table>
      <thead>
      <tr>
        <th width="250">Folder Title</th>
        <th width="350">Google Resource ID</th>
        <th width="100">Permissions</th>
      </tr>
      </thead>
      <tbody>
      <% @monitored_resources.each do |mr| %>
          <tr>
            <td><%= link_to mr.title, monitored_resource_path(mr.id) %></td>
            <td><%= mr.gid %></td>
            <td><%= mr.permissions.count %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

<%= link_to "Create new", new_monitored_resource_path, :class => 'button tiny' %>

app/views/monitored_resources/list.html.erb
<% content_for :title, 'List of Monitored Resources' %>
<h2>Monitored Resources</h2>

<%= link_to "Create new", monitored_resources_new_path, :class => 'button tiny' %>

<% unless @monitored_resource.nil? %>
<div data-alert class="alert-box info radius">
	There are no monitored resources yet.
  <a href="#" class="close">&times;</a>
</div>
<% else %>
    <table>
      <thead>
      <tr>
        <th width="250">Folder Title</th>
        <th width="350">Google Resource ID</th>
        <th width="100">Permissions</th>
      </tr>
      </thead>
      <tbody>
      <% @monitored_resources.each do |mr| %>
          <tr>
            <td><%= link_to mr.title, monitored_resource_path(mr.id) %></td>
            <td><%= mr.gid %></td>
            <td><%= mr.permissions.count %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

<%= link_to "Create new", monitored_resources_new_path, :class => 'button tiny' %>

app/views/monitored_resources/new.html.erb
<% content_for :title, 'Create new Monitored Resource' %>

<h3>Monitor a resource</h3>
<ul class="folder-list">
<% @folders.each do |folder| %>
	<li><i class="fi-folder"></i> 
		<% unless @monitored_resources_ids.include? folder['id'] %>
		<%= link_to folder['title'], create_with_path(folder['id']) %>
		<%else %>
			<%= folder['title'] %>
		<% end%>
	</li>
<% end %>
</ul>

app/views/monitored_resources/permissions.html.erb
<% content_for :title, 'Permissions for file: ' + @monitored_resource.title %>
<h2>Permissions for: <%= @monitored_resource.title %></h2>

<% unless @monitored_resource.permissions.blank? %>
    <ul>
    <% @monitored_resource.permissions.each do |permission| %>
        <li><%= permission.title  %> - <%= permission.role %></li>
    <% end %>
    </ul>
<% end %>

<%= link_to "Refresh Permissions", mr_refresh_permissions_path(@monitored_resource.id), :class => 'button tiny' %>

app/views/monitored_resources/show.html.erb
<% content_for :title, 'List of Monitored Resources' %>

<h3>Monitored Resource: <%= @monitored_resource.title %></h3>

<% if (can? :manage, @monitored_resource) %>
    <span class="has-tip" title="To update resource-list and revisions for each resource." data-tooltip>
        <%= link_to "Index Structure", index_structure_monitored_resource_path(@monitored_resource), :class => 'button tiny' %>
    </span>
    <span class="has-tip" title="To update resource metadata." data-tooltip>
        <%= link_to "Update Resources Metadata", update_resources_metadata_monitored_resource_path(@monitored_resource), :class => 'button tiny' %>
    </span>
    <span class="has-tip" title="GC Mark" data-tooltip>
        <%= link_to "GC Mark", garbage_collection_mark_monitored_resource_path(@monitored_resource), :class => 'button tiny' %>
    </span>
    <span class="has-tip" title="GC Sweep" data-tooltip>
        <%= link_to "GC Sweep", garbage_collection_sweep_monitored_resource_path(@monitored_resource), :class => 'button tiny' %>
    </span>
    <span class="has-tip" title="To aggregate revisions. Has to be done after update." data-tooltip>
        <%= link_to "Create Working Sessions", create_working_sessions_monitored_resource_path(@monitored_resource), :class => 'button tiny' %>
    </span>
    <span class="has-tip" title="To calculate the best time-distance for aggreation of revisions to working-session" data-tooltip>
        <%= link_to "Calculate Best WS-Value", calculate_all_working_sessions_monitored_resource_path(@monitored_resource), :class => 'button tiny' %>
    </span>
<% end %>

<h4>File List</h4>
<% if @monitored_resource.jobs.length > 0 %>
    <div class="callout panel">
      <span class="spin1 spinner"></span><i>Indexing in progress! Currently <%= @monitored_resource.jobs.length %> jobs are running.
      <%= link_to "Refresh status!" %></i>
    </div>
<% end %>

<% unless @monitored_resource.resources.blank? %>
    <div class="row">
      <label for="filter_periods">Filter by Period:</label>
      <% periods_array = [['--- none ---','']].concat MonitoredPeriod.all.order('start_date ASC').map { |period| [period.title, period.id] } %>
      <%= select_tag(:filter_periods, options_for_select(periods_array) ) %>
    </div>
    <div class="row">
      <label for="filter_mimetype">Filter by MimeType:</label>
      <% mimetype_array = Resource.mimetypes_for_monitored_resource(@monitored_resource.id) %>
      <%= select_tag(:filter_mimetype, options_for_select(mimetype_array) ) %>
    </div>

    <table id="files-table" data-source="<%= monitored_resource_url(@monitored_resource, :format => :json) %>">
      <thead>
      <tr>
        <th>Resource Title</th>
        <th>Created Date</th>
        <th>Last Modified Date</th>
        <th><span class="fi-page-multiple" style="padding-right: 20px;"></span></th>
        <th><span class="fi-torsos" style="padding-right: 20px;"></span></th>
        <th><span class="fi-web" style="padding-right: 20px;"></span></th>
        <th><span class="fi-comment" style="padding-right: 20px;"></span></th>
      </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
<% end %>