config/routes.rb
GdriveFeed::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # @todo: use :only => [:show, :...] in resources to be able to override create method
  get 'monitored_resources/create_with/:gid', :to => 'monitored_resources#create_with', :as => 'create_with'

  get 'calculate_time_distance_to_previous', :to => 'resources#calculate_time_distance_to_previous', :as => 'calculate_time_distance_to_previous'
  get 'calculate_optimal_threshold', :to => 'resources#calculate_optimal_threshold', :as => 'calculate_optimal_threshold'
  get 'show_threshold', :to => 'resources#show_threshold', :as => 'show_threshold'

  get 'welcome', :to => 'management/management#welcome', :as => 'welcome'
  namespace :management do
    get 'new_researcher', :to => 'management#new_researcher'
    post 'create_researcher', :to => 'management#create_researcher'
    get 'grant_access', :to => 'management#grant_access'
  end

  resources :monitored_resources do
    collection do
      get 'grant_access'
    end

    member do
      get 'index_structure'
      get 'create_working_sessions'
      get 'calculate_all_working_sessions'
      get 'update_resources_metadata'
      get 'garbage_collection_mark'
      get 'garbage_collection_sweep'
    end

    resources :permissions do
      collection do
        get 'refresh'
      end
    end

    resources :document_groups do
      collection do
        get 'new_samedocument'
      end
    end

    resources :permission_groups
    resources :resources do
      member do
        get 'refresh_revisions'
        get 'download_revisions'
        get 'merged_revisions/:rev_id', :action => :merged_revisions, :as => 'merged_revisions'
        get 'show_svg'
      end
    end
    resources :reports do
      collection do
        get 'generate'
        get 'remove'
      end
    end
  end

  get 'reports/metareport', to: 'reports#metareport', :as => 'reports_metareport'
  get 'reports/statistics', to: 'reports#statistics', :as => 'reports_statistics'
  get 'reports/generate_metareport', to: 'reports#generate_metareport', :as => 'reports_generate_metareport'

  resources :monitored_periods
  resources :period_groups

  root :to => 'management/management#welcome'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to  :monitored_resource
  belongs_to  :period_group
  
  serialize :data, Hash

  # *** DELAYED TASKS - START
  def generate_report_data
    return if monitored_resource_id.blank?

    # initialize here
    chapters = Array.new
    chapters << Report::Chapters::OverallStatisticsChapter.new
    #chapters << Report::Chapters::PermissionBasedChapter.new
    chapters << Report::Chapters::PermissionGroupBasedChapter.new

    monitored_resource ||= MonitoredResource.find(monitored_resource_id)

    if period_group_id.blank?
      monitored_periods = MonitoredPeriod.all.order start_date: :asc
    else
      period_group = PeriodGroup.find(period_group_id)
      monitored_periods = period_group.monitored_periods
    end

    data = Hash.new
    chapters.each_with_index do |chapter, index|
      chapter.calculate_for(monitored_resource, monitored_periods)
      data[index] = chapter.to_h
    end

    update_attribute(:data, data)
  end
  #handle_asynchronously :generate_report_data, :queue => 'reports', :owner => Proc.new {|o| o}


  def self.build_report_data()
    # delete old report data first
    ReportData.delete_all

    monitored_periods = MonitoredPeriod.all.order(start_date: :asc)
    metrics = Report.report_metrics

    monitored_resources = MonitoredResource.all
    monitored_resources.each do |monitored_resource|
      monitored_resource.permission_groups.each do |permission_group|
        permission_group.permissions.each do |permission|
          monitored_periods.each do |monitored_period|
            monitored_period.as_days.each do |day|
              metrics.each do |metric|

                value = metric.calculate(monitored_resource.id, day, permission.id)
                if value > 0
                  ReportData.create(
                    :metric => metric.title,
                    :value => value,
                    :date => day,
                    :monitored_resource_id => monitored_resource.id,
                    :permission_group_id => permission_group.id,
                    :permission_id => permission.id
                  )
                end
              end
            end
          end
        end
      end
    end

  end

  def self.report_metrics
    return [
        Report::Metrics::NumberOfRevisions.new
    ]
  end
end

app/models/report/chapters/abstract_chapter.rb
class Report::Chapters::AbstractChapter

  TYPE = 'CHAPTER'

  def initialize(name=nil)
    @name = name
    @sections = Array.new

    initialize_chapter
  end

  def calculate_for(monitored_resource, monitored_periods)
    @sections.each do |section|
      section.calculate_for(monitored_resource, monitored_periods)
    end
  end

  def initialize_chapter
    raise NotImplementedError.new("Subclass responsibility")
  end

  def to_h
    result = Hash.new
    result[:name] = @name
    result[:type] = TYPE
    result[:values] = Array.new
    @sections.each do |section|
      result[:values] << section.to_h
    end

    result
  end
end

app/models/report/chapters/overall_statistics_chapter.rb
class Report::Chapters::OverallStatisticsChapter < Report::Chapters::AbstractChapter
 def initialize_chapter
  @name = 'Overall Statistics'
  @sections << Report::Sections::FilesStatisticsSection.new
  @sections << Report::Sections::ActivityStatisticsSection.new
  @sections << Report::Sections::CommentsStatisticsSection.new
 end
end

app/models/report/chapters/permission_based_chapter.rb
class Report::Chapters::PermissionBasedChapter < Report::Chapters::AbstractChapter
  def initialize_chapter
    @name = 'Permission-based Statistics'

    @sections << Report::Sections::RevisionsByPermissionSection.new
    @sections << Report::Sections::FilesCreatedByPermissionSection.new
  end
end

app/models/report/chapters/permission_group_based_chapter.rb
class Report::Chapters::PermissionGroupBasedChapter < Report::Chapters::AbstractChapter
  def initialize_chapter
    @name = 'PermissionGroup-based Statistics'

    @sections << Report::Sections::WorkdaysByPermissionGroupSection.new
    @sections << Report::Sections::RevisionsByWorksdaysAndPermissionGroupSection.new
  end
end

app/models/report/metrics/abstract_metric.rb
class Report::Metrics::AbstractMetric

  TYPE = 'METRIC'

  def self.title
    raise NotImplementedError.new("Subclass responsibility")
  end

  def title
    self.class.title
  end

  def calculate_for(monitored_resource, period, data=nil)
    raise NotImplementedError.new("Subclass responsibility")
  end

end

app/models/report/metrics/abstract_permission_based_metric.rb
class Report::Metrics::AbstractPermissionBasedMetric < Report::Metrics::AbstractMetric
  def calculate_for(monitored_resource, period, permission, data=nil)
    raise NotImplementedError.new("Subclass responsibility")
  end
end

app/models/report/metrics/abstract_permission_group_based_metric.rb
class Report::Metrics::AbstractPermissionGroupBasedMetric < Report::Metrics::AbstractMetric
  def calculate_for(monitored_resource, period, permission_group)
    raise NotImplementedError.new("Subclass responsibility")
  end
end

app/models/report/metrics/chart_most_used_file_types.rb
class Report::Metrics::ChartMostUsedFileTypes < Report::Metrics::AbstractMetric

  TYPE = 'CHART'

  COLORS = {
    'image/jpeg' => '#FF0000',
    'image/png' => '#800000',
    'image/svg+xml' => '#800080',
    'application/pdf' => '#FFFF00',
    'application/vnd.google-apps.document' => '#00FFFF',
    'application/vnd.google-apps.presentation' => '#0000FF',
    'text/html' => '#8B4513',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => '#00FF00',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation' => '#008000',
    'video/quicktime' => '#FF00FF'
  }.freeze

  def self.title
    return 'Most used mime-types'
  end

  def get_color(mime_type)
    return COLORS.has_key?(mime_type) ? COLORS[mime_type] : '#000000'
  end

  def calculate_for(monitored_resource, period, data=nil)
    sql = 'SELECT resources.mime_type, COUNT(resources.id) as count
      FROM revisions JOIN resources ON revisions.resource_id=resources.id
      WHERE resources.monitored_resource_id=? AND revisions.modified_date > ? AND revisions.modified_date <= ?
      GROUP BY mime_type ORDER BY COUNT(resources.id) DESC LIMIT 4;'

    query  = ActiveRecord::Base.send(:sanitize_sql_array, [sql, monitored_resource.id, period.start_date, period.end_date])
    most_used_mimetypes = ActiveRecord::Base.connection.exec_query(query)

    result_set = Array.new
    sum_four_most_used = 0
    most_used_mimetypes.each do |mime_type|
      result_set << [ mime_type['mime_type'], mime_type['count'], get_color(mime_type['mime_type']) ]
      sum_four_most_used += mime_type['count']
    end

    sql_count_all = 'SELECT COUNT(resources.id) as count FROM revisions JOIN resources ON revisions.resource_id=resources.id
      WHERE resources.monitored_resource_id=? AND revisions.modified_date > ? AND revisions.modified_date <= ?;'
    query_count_all  = ActiveRecord::Base.send(:sanitize_sql_array, [sql_count_all, monitored_resource.id, period.start_date, period.end_date])
    remaining_revisions = ActiveRecord::Base.connection.exec_query(query_count_all)

    remaining_count = (remaining_revisions[0]['count']-sum_four_most_used)

    #result_set << [ 'REST', remaining_count, '#C0C0C0' ]

    return result_set
  end


end

app/models/report/metrics/files_created_by_permission.rb
class Report::Metrics::FilesCreatedByPermission < Report::Metrics::AbstractPermissionBasedMetric

  def calculate_for(monitored_resource, period, permission, data=nil)
    return Resource
      .where(:monitored_resource_id => monitored_resource.id)
      .where(:permission_id => permission.id)
      .where('resources.created_date > "%s" AND resources.created_date <= "%s"', period.start_date, period.end_date)
      .count()
  end
end

app/models/report/metrics/gca_indicator.rb
class Report::Metrics::GCAIndicator < Report::Metrics::AbstractMetric
  def self.title
    "GCA-Indicator"
  end

  def calculate_for(monitored_resource, period, data=nil)
    resource_ids = Collaboration.find_collaborated_resources_and_groups(monitored_resource, period, true)

    actions = Action.count(monitored_resource, period, resource_ids)
    working_sessions = WorkingSession.count(monitored_resource, period, resource_ids)
    collaborative_sessions = CollaborativeSession.count_all(monitored_resource, period, resource_ids)

    working_days = Revision.count_workdays_for(monitored_resource.id, period)

    return ((actions + working_sessions + collaborative_sessions) / working_days.to_f).round(3)
  end
end

app/models/report/metrics/illi_metric.rb
class Report::Metrics::IlliMetric < Report::Metrics::AbstractMetric
  def self.title
    "ILLI METRIC"
  end

  def calculate_for(monitored_resource, period, data=nil)
    return Collaboration.illi_metric(monitored_resource, period)
  end
end

app/models/report/metrics/number_actions.rb
class Report::Metrics::NumberActions < Report::Metrics::AbstractMetric
  def self.title
    return "# Actions"
  end

  def calculate_for(monitored_resource, period, data=nil)
    # @todo: set of resource-IDs that have been identified to be part of a (global) collaboration ...
    return Action.count(monitored_resource, period)
  end
end

app/models/report/metrics/number_average_files_created.rb
class Report::Metrics::NumberAverageFilesCreated < Report::Metrics::AbstractMetric

  def self.title
    "files created/ workdays"
  end

  def calculate_for(monitored_resource, period, data=nil)
    files = data[Report::Metrics::NumberOfFilesCreated.title][period.id]
    days = data[Report::Metrics::NumberWorkingDays.title][period.id]
    return files.to_i == 0 ? 0 : (files.to_f/ days).round(2)

    #return (data.blank? || !data.has_key?(Report::Metrics::NumberOfFilesCreated.title)) ? 0 : (data[Report::Metrics::NumberOfFilesCreated.title][period.id].to_f/ period.days).round(2)
  end
end

app/models/report/metrics/number_average_revisions.rb
class Report::Metrics::NumberAverageRevisions < Report::Metrics::AbstractMetric
  def self.title
    return "# of Revisions/ day"
  end

  def calculate_for(monitored_resource, period, data=nil)
    files = data[Report::Metrics::NumberOfRevisions.title][period.id]
    days = data[Report::Metrics::NumberWorkingDays.title][period.id]
    return files.to_i == 0 ? 0 : (files.to_f/ days).round(2)

    #return (data[Report::Metrics::NumberOfRevisions.title][period.id].to_f/period.days).round(2)
  end
end

app/models/report/metrics/number_batch_uploads.rb
class Report::Metrics::NumberBatchUploads < Report::Metrics::AbstractMetric
  def self.title
    return "# BatchUploads"
  end

  def calculate_for(monitored_resource, period, data=nil)
    return BatchUpload.count(monitored_resource, period)
  end
end

app/models/report/metrics/number_collaborated_files.rb
class Report::Metrics::NumberCollaboratedFiles < Report::Metrics::AbstractMetric
  def self.title
    return "# of collab. files"
  end

  def calculate_for(monitored_resource, period, data=nil)
    # this does not check if work has done synchronously or aynchronously, just that collaboration has taken place
    query = ActiveRecord::Base.send(:sanitize_sql_array, ["SELECT revisions.resource_id, COUNT(DISTINCT revisions.permission_id) FROM revisions JOIN resources ON revisions.resource_id=resources.id WHERE resources.monitored_resource_id=? AND (resources.modified_date > ? AND resources.modified_date <= ?) GROUP BY revisions.resource_id HAVING COUNT(DISTINCT revisions.permission_id) > 1", monitored_resource.id, period.start_date, period.end_date])
    result = ActiveRecord::Base.connection.exec_query(query)
    return result.rows.length
  end
end

app/models/report/metrics/number_collaborative_sessions.rb
class Report::Metrics::NumberCollaborativeSessions < Report::Metrics::AbstractMetric
  def self.title
    return "# collab. sessions"
  end

  def calculate_for(monitored_resource, period, data=nil)
    # synchronous working
    return CollaborativeSession.count_all(monitored_resource, period)
  end

end

app/models/report/metrics/number_comments.rb
class Report::Metrics::NumberComments < Report::Metrics::AbstractMetric
  def self.title
    return "# comments"
  end

  def calculate_for(monitored_resource, period, data=nil)
    query = ActiveRecord::Base.send(:sanitize_sql_array, ["SELECT COUNT(comments.id) AS comments FROM comments JOIN resources ON comments.resource_id=resources.id WHERE comment_id IS NULL AND resources.monitored_resource_id=? AND (comments.created_date > ? AND comments.created_date <= ?) ", monitored_resource.id, period.start_date, period.end_date])
    result = ActiveRecord::Base.connection.exec_query(query)
    result.first['comments']
  end
end

app/models/report/metrics/number_days_period.rb
class Report::Metrics::NumberDaysPeriod < Report::Metrics::AbstractMetric
    def self.title
      "# of days/ period"
    end

    def calculate_for(monitored_resource, period, data=nil)
      return period.days
    end
end

app/views/reports/index.csv.erb
<% unless @monitored_resource.reports.blank? %>
    <% period_names = Array.new %>
    <% MonitoredPeriod.all.order(start_date: :asc).each { |period| period_names << period.name } %>
Name;<%= period_names.join(";") %>
    <% @monitored_resource.reports.first.data.each do |k, chapter| %>
        <% chapter[:values].each_with_index do |section, seci| %>
            <% section[:values].each_with_index do |metric, mini| %>
<%= metric[:name] %>;<%= metric[:values].join(";" ) %>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/reports/index.html.erb
<% content_for :title, "Report for #{@monitored_resource.title}" %>

<h3>Report for: <%= @monitored_resource.title %></h3>

<% if (can? :manage, @monitored_resource) %>
    <div class="functions-bar">
<span class="has-tip" title="This will only generate reports that have not been generated1" data-tooltip>
    <%= link_to "Generate Reports", generate_monitored_resource_reports_path(@monitored_resource), :class => 'button tiny' %>
</span>
<span class="has-tip" title="This will delete all reports for a monitored resource" data-tooltip>
    <%= link_to "Delete reports", remove_monitored_resource_reports_path(@monitored_resource), :class => 'button tiny' %>
</span>
    </div>
<% end %>

<% if @monitored_resource.jobs.length > 0 %>
    <div class="callout panel">
      <span class="spin1 spinner"></span><i>Indexing in progress! Currently <%= @monitored_resource.jobs.length %> jobs are running.
      <%= link_to "Refresh status!" %></i>
    </div>
<% end %>

<% unless @monitored_resource.reports.blank? %>
    <% cols = MonitoredPeriod.all.count+1 %>
    <table>
      <thead class="analytics">
      <tr>
        <th style="width:200px;">Name</th>
        <% MonitoredPeriod.all.order(start_date: :asc).each_with_index do |period,j| %>
            <th <%= 'class="reference"'.html_safe if j.eql? 0  %>><a class="active-report-col" href="#period-<%= j+1 %>"><%= period.name %></a></th>
        <% end %>
      </tr>
      </thead>
      <tbody>

              <% report = @monitored_resource.reports.first %>
              <% report.data.each do |k, chapter| %>
                  <% unless chapter[:name].blank? %>
                      <tr>
                        <td class="table-new-chapter" colspan="<%= cols %>"><%= chapter[:name] %></td>
                      </tr>
                  <% end %>
                  <% chapter[:values].each_with_index do |section,seci| %>
                      <% unless section[:name].blank? %>
                          <tr>
                            <td></td>
                            <td class="table-new-section" colspan="<%= cols %>"><%= section[:name] %></td>
                          </tr>
                      <% end %>
                      <% section[:values].each_with_index do |metric,mini| %>
                          <tr>
                            <td><% if metric[:type] == 'METRIC' %><b><%= metric[:name] %></b><% else %><%= metric[:name] %><% end %></td>
                            <% metric[:values].each_with_index do |value,l| %>
                                <% classes = (l.eql? 0) ? 'reference ' : '' %>
                                <% classes += value.is_a?(Array) ? '' : 'isnumber' %>
                                <td class="<%= classes %>"><%= value %></td>
                            <% end %>
                          </tr>
                      <% end %>
                  <% end %>
              <% end %>
              </tbody>
            </table>
          </div>
      <% end %>

app/views/reports/index_old.html.erb
<% content_for :title, "Report for #{@monitored_resource.title}" %>

<h3>Report for: <%= @monitored_resource.title %></h3>

<% if (can? :manage, @monitored_resource) %>
<div class="functions-bar">
<span class="has-tip" title="This will only generate reports that have not been generated1" data-tooltip>
    <%= link_to "Generate Reports", generate_monitored_resource_reports_path(@monitored_resource), :class => 'button tiny' %>
</span>
<span class="has-tip" title="This will delete all reports for a monitored resource" data-tooltip>
    <%= link_to "Delete reports", remove_monitored_resource_reports_path(@monitored_resource), :class => 'button tiny' %>
</span>
</div>
<% end %>

<% if @monitored_resource.jobs.length > 0 %>
    <div class="callout panel">
      <span class="spin1 spinner"></span><i>Indexing in progress! Currently <%= @monitored_resource.jobs.length %> jobs are running.
      <%= link_to "Refresh status!" %></i>
    </div>
<% end %>

<% unless @monitored_resource.reports.blank? %>
    <% chart_value_sets = Hash.new %>

    <dl id="report-tabs" class="tabs" data-tab>
      <% @period_groups.each_with_index do |period_group, index| %>
        <%
           group_icon = "<span class=\"fi-#{period_group.logo_class}\"></span> ".html_safe
        %>
        <dd <%= 'class="active"'.html_safe if index == 0 %>>
          <a class="report-tab-link" href="#panel2-<%= index %>"><span class="fi-<%= period_group.logo_class %>"></span> <%= period_group.name %> (<%= period_group.monitored_periods.length %>)</a>
        </dd>
      <% end %>
    </dl>
    <div class="tabs-content">
      <% @period_groups.each_with_index do |period_group, index| %>

          <div class="report-tab content<%= ' active' if index == 0 %>" id="panel2-<%= index %>">
            <h4 class="report-table-header <%= 'first-header' if index == 0%>"><%= period_group.name %></h4>
            <table>
              <thead class="analytics">
              <tr>
                <th>Name</th>
                <% period_group.monitored_periods.each_with_index do |period,j| %>

                    <th <%= 'class="reference"'.html_safe if j.eql? 0  %>><a class="active-report-col" href="#period-<%= j+1 %>"><%= period.name %></a></th>
                <% end %>
              </tr>
              </thead>
              <tbody>
              <% report = @monitored_resource.report_for_period_group(period_group) %>
              <% report.data.each do |k, chapter| %>
                <% unless chapter[:name].blank? %>
                  <tr>
                    <td class="table-new-chapter" colspan="<%= period_group.monitored_periods.length+1 %>"><%= chapter[:name] %></td>
                  </tr>
                <% end %>
                <% chapter[:values].each_with_index do |section,seci| %>
                      <% unless section[:name].blank? %>
                          <tr>
                            <td></td>
                            <td class="table-new-section" colspan="<%= period_group.monitored_periods.length %>"><%= section[:name] %></td>
                          </tr>
                      <% end %>
                      <% section[:values].each_with_index do |metric,mini| %>
                        <tr>
                          <td><% if metric[:type] == 'METRIC' %><b><%= metric[:name] %></b><% else %><%= metric[:name] %><% end %></td>
                          <% metric[:values].each_with_index do |value,l| %>
                            <% classes = (l.eql? 0) ? 'reference ' : '' %>
                            <% classes += value.is_a?(Array) ? '' : 'isnumber' %>
                            <td class="<%= classes %>">
                              <% if value.is_a?(Array) %>
                                  <ul style="font-size: 80%;">
                                  <% value.each do |value_array| %>
                                    <li><%= value_array[0].split('/').last.split('.').last %>: <%= value_array[1] %></li>
                                  <% end %>
                                  </ul>
                              <% elsif value.is_a?(Hash) %>
                                  <ul style="font-size: 80%;">
                                    <% the_hash = value.sort_by {|k,v| v}.reverse %>
                                    <% the_hash.each do |day,count| %>
                                        <li><%= day %>: <%= count %></li>
                                    <% end %>
                                  </ul>
                              <% else %>
                                <%= value %>
                              <% end %>
                            </td>
                          <% end %>
                        </tr>
                      <% end %>
                <% end %>
              <% end %>
              </tbody>
            </table>
          </div>
      <% end %>
    </div>
<% end %>

app/views/reports/metareport.html.erb
<% content_for :title, "MetaReport" %>

<h2>MetaReport</h2>
<div class="large-3 columns">
    <ul class="side-nav">
    <% @metrics.each_with_index do |metric_name,metric_index| %>
        <li <%= 'class="active"'.html_safe if metric_index == 0 %>><a data-metric-name="<%= metric_name %>" href="#" class="metric-link "><%= metric_name %></a></li>
    <% end %>
    </ul>
</div>
<div class="large-9 columns">
    <div id="metareport-chart" class="metareport-charts" style="width:100%; height:800px;"></div>
</div>

app/views/reports/statistics.html.erb
<% content_for :title, "General System Statistics" %>

<h2>General System Statistics</h2>
<p>Recording since <%= @dates['min'].to_s(:db) %>, for <%= time_difference(@dates['min'], @dates['max']) %> hours </p>

<h3>Resources and Revisions</h3>
<table>
  <thead><tr><th>Metric</th><th>Count</th><th>Percentage</th></tr></thead>
  <tbody>
    <tr><td>Number of Files</td><td><%= @resource_count %></td><td></td></tr>
    <tr><td>Number of Revisions</td><td><%= @revisions_count %></td><td></td></tr>
    <tr>
      <td>Number of Google Docs</td><td><%= @google_count %></td>
      <td><%= ((100/@resource_count.to_f)*@google_count).round(2) %>%</td>
    </tr>
    <tr>
      <td>Number of revisions from Google Docs</td><td><%= @revision_google_count %></td>
      <td><%= ((100/@revisions_count.to_f)*@revision_google_count).round(2) %>%</td>
    </tr>
    <tr>
      <td>Number of MS-Office Documents</td><td><%= @office_count %></td>
      <td><%= ((100/@resource_count.to_f)*@office_count).round(2) %>%</td>
    </tr>
    <tr>
      <td>Number of OpenOffice Documents</td><td><%= @openoffice_count %></td>
      <td><%= ((100/@resource_count.to_f)*@openoffice_count).round(2) %>%</td>
    </tr>
    <tr>
      <td>Number of Images</td><td><%= @images_count %></td>
      <td><%= ((100/@resource_count.to_f)*@images_count).round(2) %>%</td>
    </tr>
    <tr>
      <td>Number of Images with single revision</td><td><%= @resource_single_images %></td>
      <td><%= ((100/@resource_count.to_f)*@resource_single_images).round(2) %>%</td>
    </tr>
    <tr>
      <td>Number of files with single revision</td><td><%= @resource_single %></td>
      <td><%= ((100/@resource_count.to_f)*@resource_single).round(2) %>%</td>
    </tr>
    <tr>
      <td>Number of Resources with single revision, same datetime</td><td><%= @resource_single_same_latest %></td>
      <td><%= ((100/@resource_count.to_f)*@resource_single_same_latest).round(2) %>%</td>
    </tr>
    <tr>
      <td>Number of Resources with single revision, datetime different</td><td><%= @resource_single_different_latest %></td>
      <td><%= ((100/@resource_count.to_f)*@resource_single_different_latest).round(2) %>%</td>
    </tr>
    <tr>
      <td>Number of Resources with single revision, datetime eql. 1</td><td><%= @resource_single_latest_eql_one %></td>
      <td><%= ((100/@resource_count.to_f)*@resource_single_latest_eql_one).round(2) %>%</td>
    </tr>
  </tbody>
</table>

<h3>Top 15 Mime-Types <small>from <%= @resource_count %> resources (* folders have been excluded)</small></h3>
<% unless @mime_count.blank? %>
    <table>
      <thead><tr><th>Mime-Type</th><th>Count</th><th>Percentage</th></tr></thead>
      <tbody>
      <% @mime_count.each do |row| %>
          <tr>
            <td><%= row['mime_type'] %></td>
            <td> <%= row['count'] %></td>
            <td> <%= ((row['count'].to_f/ @resource_count) * 100).round(2) %>%</td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

<h3>Top 15 Mime-Types and their number of revisions plotted</h3>
<div id="mimetype-boxplot" style="width: 1000px; height: 600px;"></div>