config/routes.rb
GdriveFeed::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # @todo: use :only => [:show, :...] in resources to be able to override create method
  get 'monitored_resources/create_with/:gid', :to => 'monitored_resources#create_with', :as => 'create_with'

  get 'calculate_time_distance_to_previous', :to => 'resources#calculate_time_distance_to_previous', :as => 'calculate_time_distance_to_previous'
  get 'calculate_optimal_threshold', :to => 'resources#calculate_optimal_threshold', :as => 'calculate_optimal_threshold'
  get 'show_threshold', :to => 'resources#show_threshold', :as => 'show_threshold'

  get 'welcome', :to => 'management/management#welcome', :as => 'welcome'
  namespace :management do
    get 'new_researcher', :to => 'management#new_researcher'
    post 'create_researcher', :to => 'management#create_researcher'
    get 'grant_access', :to => 'management#grant_access'
  end

  resources :monitored_resources do
    collection do
      get 'grant_access'
    end

    member do
      get 'index_structure'
      get 'create_working_sessions'
      get 'calculate_all_working_sessions'
      get 'update_resources_metadata'
      get 'garbage_collection_mark'
      get 'garbage_collection_sweep'
    end

    resources :permissions do
      collection do
        get 'refresh'
      end
    end

    resources :document_groups do
      collection do
        get 'new_samedocument'
      end
    end

    resources :permission_groups
    resources :resources do
      member do
        get 'refresh_revisions'
        get 'download_revisions'
        get 'merged_revisions/:rev_id', :action => :merged_revisions, :as => 'merged_revisions'
        get 'show_svg'
      end
    end
    resources :reports do
      collection do
        get 'generate'
        get 'remove'
      end
    end
  end

  get 'reports/metareport', to: 'reports#metareport', :as => 'reports_metareport'
  get 'reports/statistics', to: 'reports#statistics', :as => 'reports_statistics'
  get 'reports/generate_metareport', to: 'reports#generate_metareport', :as => 'reports_generate_metareport'

  resources :monitored_periods
  resources :period_groups

  root :to => 'management/management#welcome'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= favicon_link_tag "favicon.ico" %>

  <title>GDrive Feed: <%= content_for?(:title) ? yield(:title) : "" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag 'application-print', :media => 'print' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>

<body>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#"><%= image_tag("gdrive-logo.svg", :alt => "Google Drive", :width => '35') %> Goolge Drive Monitor</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <%= render_navigation(:context => :user) %>
  </section>
</nav>
<!-- Main Page Content and Sidebar -->

<div id="sidebar-nav" class="sidebar small-2 columns">
  <% if user_signed_in? %>
  <nav>
    <%= render_navigation %>
  </nav>
  <% end %>
</div>
<div class="small-10 columns content">
  <!-- sub-navigation //-->
  <% if !@monitored_resource.blank? and @resource.blank? and (can? :manage, @monitored_resource) %>
      <div data-magellan-expedition="fixed">
        <dl class="sub-nav">
          <dt>Monitored Resource:</dt>
          <dd class="<%= 'active' if current_page?( monitored_resource_url(@monitored_resource)) %>">
            <%= link_to 'List Files', monitored_resource_path(@monitored_resource) %>
          </dd>
          <dd class="<%= 'active' if current_page?( monitored_resource_document_groups_url(@monitored_resource)) %>">
            <%= link_to 'Document Groups', monitored_resource_document_groups_path(@monitored_resource) %>
          </dd>
          <dd class="<%= 'active' if current_page?( monitored_resource_permissions_url(@monitored_resource) ) %>">
            <%= link_to 'Permissions', monitored_resource_permissions_path(@monitored_resource) %>
          </dd>
          <dd class="<%= 'active' if current_page?( monitored_resource_permission_groups_url(@monitored_resource) ) %>">
            <%= link_to 'Permission Groups', monitored_resource_permission_groups_path(@monitored_resource) %>
          </dd>
        </dl>
      </div>
  <% end %>

  <% if flash[:notice] %>
      <div data-alert class="alert-box info radius">
        <%= flash[:notice] %>
        <a href="#" class="close">&times;</a>
      </div>
  <% end %>
  <% if flash[:warning] %>
      <div data-alert class="alert-box warning radius">
        <%= flash[:warning] %>
        <a href="#" class="close">&times;</a>
      </div>
  <% end %>
  <% if flash[:alert] %>
      <div data-alert class="alert-box alert radius">
        <%= flash[:alert] %>
        <a href="#" class="close">&times;</a>
      </div>
  <% end %>
  <%= yield %>
</div>

<%= javascript_include_tag "application" %>
<%= javascript_include_tag params[:controller] %>
</body>
</html>